name: ubik
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_launcher_icons:

  #Estado
  provider: ^6.0.2
  shared_preferences: ^2.0.15

  #FIREBASE
  firebase_core: ^1.19.2
  firebase_storage: ^10.3.2
  firebase_auth: ^3.3.18
  cloud_firestore: ^3.1.0

  #IMAGE
  image_picker: ^0.8.5+3
  image_cropper: ^2.0.3

  #UTILS
  fluttertoast: ^8.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/image/logo_app.png"
  adaptive_icon_background: "assets/image/logo_app.png"

flutter:
  uses-material-design: true
  assets:
    - assets/image/
    - assets/image/bands/
  fonts:
    - family: Montserrat-Black
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Black.ttf
          weight: 700
    - family: Montserrat-Bold
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Bold.ttf
          weight: 700
    - family: Montserrat-Light
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Light.ttf
          weight: 700
    - family: Montserrat-Medium
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Medium.ttf
          weight: 700
    - family: Montserrat-Regular
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Regular.ttf
          weight: 700
    - family: Montserrat-SemiBold
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-SemiBold.ttf
          weight: 700
    - family: Montserrat-Thin
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Thin.ttf
          weight: 700