name: ubik
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_launcher_icons:

  #Estado
  provider: ^6.0.2
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/image/logo_app.png"
  adaptive_icon_background: "assets/image/logo_app.png"

flutter:
  uses-material-design: true
  assets:
    - assets/image/
    - assets/image/bands/